services:
  - type: web
    name: bull-back-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://bull-back-api.onrender.com
